# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='in_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
